// Scene 8 "The Open Box" — hand over the keyboard.
//
// Free-text recall against the deal's memory. Three states, and the second two are the
// reason this scene is worth showing at all:
//
//   LIVE            recalled from memory, answered by the model, sources listed
//   REPLAY          the model was unreachable; a frozen answer captured earlier is shown,
//                   labelled REPLAY so nobody mistakes cached for live
//   NOT IN MEMORY   the question is outside what was ingested. It says so and states what
//                   it does cover, rather than inventing something plausible.
//
// The frozen replay is generated by scripts/freeze-replay.mjs from real live runs — it is
// captured output, never hand-written answers.
import { readFileSync } from "node:fs";
import { loadEnv, searchDomain, listMemories, DOMAIN_SCOPE } from "./xtrace.js";
import { redact } from "./redact.js";

const env = loadEnv();
const REPLAY_FILE = new URL("../fixtures/replay/openbox.json", import.meta.url);

// Below this, treat the corpus as simply not containing the answer. Tuned against the
// live corpus: on-topic questions score ~0.75+, off-topic ones fall well below.
const RELEVANCE_FLOOR = 0.55;

const SYSTEM =
  "You are answering questions about a private-credit loan strictly from the recalled memory " +
  "provided. Answer in at most three sentences. Quote figures exactly as they appear. " +
  "If the recalled memory does not contain the answer, say so plainly — never guess.";

export const SUGGESTED = [
  "What did we believe about Thornwick's Q1 2026 leverage in May 2026, and what changed?",
  "Has this borrower restated before?",
  "Who signed the last compliance certificate?",
  "What happened to the covenant breach?",
  "What is the share price of Apple?",
];

function replayBank() {
  try {
    return JSON.parse(readFileSync(REPLAY_FILE, "utf8"));
  } catch {
    return { captured: null, answers: {} };
  }
}

const norm = (q) => String(q || "").toLowerCase().replace(/[^a-z0-9 ]/g, "").replace(/\s+/g, " ").trim();

// What the memory actually covers, computed from the corpus rather than asserted.
let coverageCache = null;
export async function coverage() {
  if (coverageCache) return coverageCache;
  try {
    const rows = await listMemories({ ...DOMAIN_SCOPE, limit: 200 });
    const names = new Set();
    for (const m of rows.data ?? []) {
      // Fixed names, not a greedy pattern — a loose match produced near-duplicate variants
      // of the same borrower and reported seven "deals" where the corpus holds three.
      for (const name of ["Thornwick Logistics", "Halveston Services", "Ardenmoor Capital"]) {
        if ((m.text || "").includes(name)) names.add(name);
      }
    }
    coverageCache = { deals: [...names], memories: (rows.data ?? []).length };
  } catch {
    coverageCache = { deals: [], memories: null };
  }
  return coverageCache;
}

async function callModel(question, context) {
  if (!env.NOVITA_API_KEY || !env.NOVITA_MODEL) throw new Error("model not configured");
  const r = await fetch("https://api.novita.ai/openai/v1/chat/completions", {
    method: "POST",
    headers: { "content-type": "application/json", authorization: `Bearer ${env.NOVITA_API_KEY}` },
    body: JSON.stringify({
      model: env.NOVITA_MODEL,
      messages: [
        { role: "system", content: SYSTEM },
        { role: "system", content: `Recalled memory:\n${context}` },
        { role: "user", content: question },
      ],
      temperature: 0,
      max_tokens: 700,
    }),
  });
  if (!r.ok) throw new Error(`model ${r.status}`);
  const j = await r.json();
  const text = (j.choices?.[0]?.message?.content || "").trim();
  if (!text) throw new Error("model returned an empty answer");
  return text;
}

export async function ask(question, { allowLive = true } = {}) {
  const q = String(question || "").trim();
  if (!q) return { state: "empty", label: "—", question: q };

  let rows = [];
  let searchFailed = null;
  try {
    const r = await searchDomain(q, 6);
    rows = (r?.data ?? []).filter((m) => (m.score ?? 0) >= RELEVANCE_FLOOR);
  } catch (e) {
    searchFailed = redact(e.message);
  }

  // Nothing relevant: say so, and say what IS here. This is the credibility state.
  if (!searchFailed && !rows.length) {
    return { state: "not-in-memory", label: "NOT IN MEMORY", question: q, coverage: await coverage() };
  }

  const context = rows.map((m) => `- ${m.text}`).join("\n");
  const sources = rows.map((m) => ({ text: m.text, conv_id: m.conv_id, score: m.score }));

  if (allowLive && !searchFailed) {
    try {
      return { state: "live", label: "LIVE", question: q, answer: await callModel(q, context), sources };
    } catch { /* fall through to replay */ }
  }

  const bank = replayBank();
  const frozen = bank.answers?.[norm(q)];
  if (frozen) {
    return { state: "replay", label: "REPLAY", question: q, answer: frozen.answer,
             sources: frozen.sources ?? sources, captured: bank.captured };
  }

  return { state: "unavailable", label: "NO ANSWER", question: q, sources,
           why: searchFailed ? `memory unreachable (${searchFailed})` : "the model was unreachable and this question is not in the frozen replay" };
}
